name: CI/CD Éventis

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests PHPUnit
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: eventis_test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: admin
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo_mysql, mbstring, intl, zip, bcmath, opcache

      - name: Install dependencies
        working-directory: backend
        run: composer install --no-interaction --prefer-dist

      - name: Copy .env
        working-directory: backend
        run: cp .env.example .env

      - name: Set environment variables
        working-directory: backend
        run: |
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=eventis_test/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=admin/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' .env

      - name: Generate app key
        working-directory: backend
        run: php artisan key:generate

      - name: Run migrations
        working-directory: backend
        run: php artisan migrate --force

      - name: Run tests
        working-directory: backend
        run: php artisan test

  deploy:
    name: Deploy sur Railway
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy backend
        run: railway redeploy --service 0700b3bd-a96f-4235-b7d0-eb079f408593 --environment 3b7340c5-680f-414c-a122-5bdf839bc0ea --yes
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy frontend
        run: railway redeploy --service 3b29ea76-a1f7-4cac-8967-d23698f6f259 --environment 3b7340c5-680f-414c-a122-5bdf839bc0ea --yes
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}